### ISSUE TITLE
Error building production version

### ISSUE THREAD

**Issue by saimirg** [flexn-io/create#77] opened 2023-04-30 19:54 UTC
Hi, I'm getting the following errors when trying to build a Production or Canary version for android TV. The Debug version is being build fine 

`│ [ error ] [run] COMMAND:

gradlew.bat assembleRelease -x bundleReleaseJsAndAssets

FAILED with ERROR:

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-reanimated:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
 > Android resource linking failed
 ERROR:C:\Users\saimirgora\.gradle\caches\transforms-3\a67a1412ab926e2cbf316ee1c973ebf8\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lSta
r not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':flexn-io-sdk:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
 > Android resource linking failed
 ERROR:C:\Users\saimirgora\.gradle\caches\transforms-3\a67a1412ab926e2cbf316ee1c973ebf8\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lSta
r not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-safe-area-context:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
 > Android resource linking failed
 ERROR:C:\Users\saimirgora\.gradle\caches\transforms-3\a67a1412ab926e2cbf316ee1c973ebf8\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lSta
r not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

Command failed with exit code 1: gradlew.bat assembleRelease -x bundleReleaseJsAndAssets
Note: C:\node-projects\flexnje\node_modules\@flexn\sdk\android\src\main\java\io\flexn\sdk\TvRemoteHandlerModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\node-projects\flexnje\node_modules\react-native-reanimated\android\src\main\java\com\swmansion\reanimated\NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.10/998caa30623f73223194a8b657abd2baec4880ea/kotlin-stdlib-jdk8-1.4.10.jar (version
1.4)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.10/30e46450b0bb3dbf43898d2f461be4a942784780/kotlin-stdlib-jdk7-1.4.10.jar (version
1.4)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.20/9be77b243a362b745e365f286627b8724337009c/kotlin-stdlib-1.4.20.jar (version 1.4)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.20/c6761d7805b5312302f2bbd78cda68c976ce0c70/kotlin-stdlib-common-1.4.20.jar (vers
ion 1.4)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar (version
1.6)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.10/c118700e3a33c8a0d9adc920e9dec0831171925/kotlin-stdlib-common-1.6.10.jar (versi
on 1.6)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar (version
1.6)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar (version 1.6)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.10/ea29e063d2bbe695be13e9d044dcfb0c7add398e/kotlin-stdlib-1.4.10.jar (version 1.4)
    C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.10/6229be3465805c99db1142ad75e6c6ddeac0b04c/kotlin-stdlib-common-1.4.10.jar (vers
ion 1.4)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.6.10/e80fe6ac3c3573a80305f5ec43f86b829e8ab53d/kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/
kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.10/c118700e3a33c8a0d9adc920e9dec0831171925/kotlin-stdlib-common-1.6.10.jar!/META-I
NF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: C:/Users/saimirgora/.gradle/caches/transforms-3/c60cfcebd52fc4fdec006b2df9f27493/transformed/jetified-react-native-0.71.0-rc.0-release/jars/classes.jar!/META-INF/ReactAndroid_release.
kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.10/e1c380673654a089c4f0c9f83d0ddfdc1efdb498/kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/
kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
e: C:/Users/saimirgora/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-std
lib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-reanimated:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\saimirgora\.gradle\caches\transforms-3\a67a1412ab926e2cbf316ee1c973ebf8\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/
lStar not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':flexn-io-sdk:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\saimirgora\.gradle\caches\transforms-3\a67a1412ab926e2cbf316ee1c973ebf8\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/
lStar not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-safe-area-context:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\saimirgora\.gradle\caches\transforms-3\a67a1412ab926e2cbf316ee1c973ebf8\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/
lStar not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 2s
Configuration on demand is an incubating feature.

> Configure project :app
WARNING:: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View B
inding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

> Configure project :react-native-reanimated
WARNING:: The specified Android SDK Build Tools version (28.0.0) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.`

**Comment by pauliusguzas** [comment] 2023-05-16 07:05
Hello, @saimirg. Thanks for reporting an issue. We tried to reproduce on main branch using flexn/template but couldn't, could you please provide more details of your environment, versions which you are using, commands which you are running?

**Comment by saimirg** [comment] 2023-05-16 11:15
@pauliusguzas logs above were copied from a windows machine, however we have had the same behaviour on other windows machines as well as MAC PCs

The way we could build a release version for android is by adding "app" prefix to command: `gradlew app:assembleRelease -x bundleReleaseJsAndAssets`

**Comment by pauliusguzas** [comment] 2023-06-02 09:21
@saimirg could you provide your `renative.json` from  appConfigs?

**Comment by mihaiblaga89** [comment] 2023-06-17 21:34
@pauliusguzas might be related to #91, that's caused by missing plugins and by the looks of it the error complains that it can't find some plugins

**Comment by mihaiblaga89** [comment] 2023-06-27 22:12
closing, feel free to reopen if it doesn't work with latest version

**Closed by mihaiblaga89** 2023-06-27 22:12 UTC
