### ISSUE TITLE
[Regression] [android, androidTV] @flexn/create-template-starter doesn't run on android and androidtv

### ISSUE THREAD

**Issue by GabrieleKaceviciute** [flexn-io/create#135] opened 2023-07-18 14:50 UTC
rnv version: 0.37.1
flexn/create-template-starter version: 0.21.4-rc.1

**To Reproduce**
1. Create new project with `rnv new` and choose `@flexn/create-template-starter@0.21.4-rc.1`
2. Run `rnv run -p android` -> error occurs 

**Screenshots or copy&paste**
`rnv run -p android` / `rnv run -p android -d`
[android.txt](https://github.com/flexn-io/create/files/12081860/android.txt)

`rnv run -p androidtv`
[androidtv.txt](https://github.com/flexn-io/create/files/12081776/androidtv.txt)

**Desktop (please complete the following information):**

-   OS: macOS Monterey 12.6
-   Node Version: 16.14.2
-   RNV Version: 0.37.1

**Comment by aurimasmi** [comment] 2023-07-18 16:08
It's your project issue. As error `says tag is not a valid Android package name: 'com.mycompany.create21.4'` you gave your app name `com.mycompany.create21.4  which is invalid there can’t be numbers there. It’s not a bug, I'm closing this issue

**Closed by aurimasmi** 2023-07-18 16:08 UTC
